model_params:
  name: 'ConditionalVAE'
  in_channels: 3
  num_classes: 105
  latent_dim: 128

  vocab_size: 9902
  embedding_size: 100
  encoder_hidden_size: 100
  num_layers: 2
  bidirectional: True
  dropout: 0.1

  decoder_hidden_size: 100
  word_drop: 0.0
  max_unroll: 50
  sample: False
  temperature: 1.0
  beam_size: 5
  bow: True
  activation: 'Tanh'

data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.01 #0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.0025 #0.00025
  manual_seed: 1265
  bow_weight: 0.5

trainer_params:
  gpus: [1] #[1]
  max_epochs: 10

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE"
